### ISSUE TITLE
License for repo content and images

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [nicolocarpignoli/artoolkit-barcode-markers-collection#2]
Hi @nicolocarpignoli thanks for putting this together. 

I've created a prototype website to render some AR things for biomedical engineering students, and to perhaps experiment with AR based assisted surgery. https://github.com/scanAR/scanar.github.io

I am currently shipping image 206 from your repository but want to add more. So far I've set the MIT license for my project: https://github.com/scanAR/scanar.github.io/blob/master/LICENSE

I was wondering if you are happy for others to use/re-use these images. If so under what license would you have people share/use these? Can you provide guidance as to how to credit your efforts? I'll add a message on the readme to highlight the source of the image but please do let me know if you prefer for me to cite/refer to you in another way or to mention a particular license.

**Comment by nicolocarpignoli** [comment]
Hi there,

absolutely no problem, you do not have to cite ME explicitly because I do not own these markers, I just collected them.
I think the correct License to be used is the "artoolkit" License (do not remember what is).
I link you to the repository: https://github.com/artoolkitx/jsartoolkit5

BTW: the link above is the jsartoolkit, the original artoolkit is no longer maintained: https://www.wikiwand.com/en/ARToolKit

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks, that is great.
